language: go

dist: disco
sudo: false

matrix:
  include:
  - go: 1.13.x
    env: GO111MODULE=on

addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"

install:
  - set -e
  - export PROTOBUF_VERSION=3.8.0
  - export PROTOC_FILENAME=protoc-${PROTOBUF_VERSION}-linux-x86_64.zip
  - wget -O $HOME/${PROTOC_FILENAME} https://github.com/google/protobuf/releases/download/v${PROTOBUF_VERSION}/${PROTOC_FILENAME}
  - unzip $HOME/${PROTOC_FILENAME} -d $HOME
  - protoc --version
  - go get github.com/golang/protobuf/protoc-gen-go@v1.3.2
  - type protoc-gen-go

  - pyenv global 3.6 || pyenv global 3.7 || pyenv global 3.8
  - python --version|grep -i 'python 3'
  - python -m pip install --user grpcio
  - python -m pip install --user grpcio-tools
  - python -m grpc_tools.protoc --version

script:
  - make build
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
