#!/bin/bash

echo "Deploy parsing-core"
cd /usr/lib/yandex/combaine/core-apps/parsing-core/
./deploy.sh

echo "Deploy cfgmanager"
cd /usr/lib/yandex/combaine/core-apps/cfgmanager/
./deploy.sh

echo "Deploy parsing-app"
cd /usr/lib/yandex/combaine/core-apps/parsing-app/
./deploy.sh

# echo "Deploy timetail"
# cd /usr/lib/yandex/combaine/core-apps/timetail/
# ./deploy.sh

echo "Deploy average"
cd /usr/lib/yandex/combaine/core-apps/aggregate-average/
./deploy.sh

cd /usr/lib/yandex/combaine/core-apps/aggregate-quant/
./deploy.sh

echo "Deploy aggregate"
cd /usr/lib/yandex/combaine/core-apps/aggregate-core/
./deploy.sh

echo "Deploy agave"
cd /usr/lib/yandex/combaine/core-apps/agave/
./deploy.sh

echo "Deploy juggler"
cd /usr/lib/yandex/combaine/core-apps/juggler/
./deploy.sh
#DEBHELPER#
