#!/bin/bash

set -e

case $1 in
    configure)
		echo "Deploy parsing-core"
		cd /usr/lib/yandex/combaine/core-apps/parsing-core/
		./deploy.sh

		echo "Deploy parsing-app"
		cd /usr/lib/yandex/combaine/core-apps/parsing-app/
		./deploy.sh

		echo "Deploy custom"
		cd /usr/lib/yandex/combaine/core-apps/aggregate-custom/
		./deploy.sh

		echo "Deploy aggregate"
		cd /usr/lib/yandex/combaine/core-apps/aggregate-core/
		./deploy.sh

		echo "Deploy agave"
		cd /usr/lib/yandex/combaine/core-apps/agave/
		./deploy.sh

		echo "Deploy juggler"
		cd /usr/lib/yandex/combaine/core-apps/juggler/
		./deploy.sh

		echo "Deploy graphite"
		cd /usr/lib/yandex/combaine/core-apps/graphite/
		./deploy.sh

		echo "Deploy razladki"
		cd /usr/lib/yandex/combaine/core-apps/razladki/
		./deploy.sh

		echo "Deploy cbb"
		cd /usr/lib/yandex/combaine/core-apps/cbb/
		./deploy.sh

		echo "Deploy solomon"
		cd /usr/lib/yandex/combaine/core-apps/solomon/
		./deploy.sh
        ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        ;;

    *)
        echo "postinst called with an unknown argument \`$1'" >&2
        ;;
esac

#DEBHELPER#

exit 0
